/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Routes;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author tales
 */
public class Interfeca extends javax.swing.JFrame {

    /**
     * Creates new form Interfeca
     */
    public Interfeca() {
        initComponents();
        jTabbedPane1.enable(false);
        
        
        
    }
    Routes rotas = new Routes();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        login_input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        senha_input = new javax.swing.JTextField();
        login_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lstarVendas_btn = new javax.swing.JButton();
        listarClientes_btn = new javax.swing.JButton();
        ListarEstoque_btn = new javax.swing.JButton();
        listarColaboradores_btn = new javax.swing.JButton();
        sair_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        numeroClientesColaboradores_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        incluirCliente_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nome_c = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email_txt = new javax.swing.JLabel();
        endereco_txt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cpf_txt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email_c = new javax.swing.JTextField();
        end_c = new javax.swing.JTextField();
        telefone_c = new javax.swing.JTextField();
        telegonetelefone_c = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        login_c = new javax.swing.JTextField();
        senhasenha_c = new javax.swing.JTextField();
        cpfCpf_c = new javax.swing.JTextField();
        castrarClaborador_btn = new javax.swing.JButton();
        alterarCliente_c = new javax.swing.JButton();
        alterarColaborador_c = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        excluirColaboradorCliente_c = new javax.swing.JTextField();
        excluirColaborador_btn = new javax.swing.JButton();
        excluirCliente_btn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        excluirMaterial_c = new javax.swing.JTextField();
        excluirMaterial_btn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        inputCpfVenda_c = new javax.swing.JTextField();
        inputNomeMaterial_c = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        inputQuantidadeMaterial_c = new javax.swing.JTextField();
        realizarVendas_btn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nomeMaterial_c = new javax.swing.JTextField();
        preco_c = new javax.swing.JTextField();
        quantidade_c = new javax.swing.JTextField();
        especificacao_c = new javax.swing.JTextField();
        margemLucro_c = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fornecedor_c = new javax.swing.JTextField();
        adicionarMaterial_btn = new javax.swing.JButton();
        alterarMaterial_btn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        dataFabricacao_c = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        input_cpfExtrato = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        campo_extrato = new javax.swing.JTextArea();
        gerar_btn = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite seu Login");

        jLabel2.setText("Digite sua senha");

        senha_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha_inputActionPerformed(evt);
            }
        });

        login_btn.setText("Logar");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(senha_input, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(login_input, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(login_btn)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(login_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(senha_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(login_btn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("Login", jPanel2);

        lstarVendas_btn.setText("Listar Vendas");
        lstarVendas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstarVendas_btnActionPerformed(evt);
            }
        });

        listarClientes_btn.setText("Listar Clientes");
        listarClientes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarClientes_btnActionPerformed(evt);
            }
        });

        ListarEstoque_btn.setText("Estoque");
        ListarEstoque_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarEstoque_btnActionPerformed(evt);
            }
        });

        listarColaboradores_btn.setText("Listar Colaboradores");
        listarColaboradores_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarColaboradores_btnActionPerformed(evt);
            }
        });

        sair_btn.setText("SAIR");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        numeroClientesColaboradores_btn.setText("N° Col&cli");
        numeroClientesColaboradores_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroClientesColaboradores_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lstarVendas_btn)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sair_btn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(listarClientes_btn)
                        .addGap(18, 18, 18)
                        .addComponent(listarColaboradores_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroClientesColaboradores_btn)
                        .addGap(36, 36, 36)
                        .addComponent(ListarEstoque_btn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 142, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sair_btn)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lstarVendas_btn)
                    .addComponent(listarClientes_btn)
                    .addComponent(ListarEstoque_btn)
                    .addComponent(listarColaboradores_btn)
                    .addComponent(numeroClientesColaboradores_btn))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Listar", jPanel3);

        incluirCliente_btn.setText("Cadastrar Cliente");
        incluirCliente_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirCliente_btnActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar Colaborador");

        jLabel3.setText("Nome");

        email_txt.setText("e-mail");

        endereco_txt.setText("Endereço");

        jLabel6.setText("Telefone");

        cpf_txt.setText("CPF");

        jLabel4.setText("Login");

        jLabel5.setText("Senha");

        end_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end_cActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        castrarClaborador_btn.setText("Castrar Colaborador");
        castrarClaborador_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castrarClaborador_btnActionPerformed(evt);
            }
        });

        alterarCliente_c.setText("Alterar Cliente");
        alterarCliente_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarCliente_cActionPerformed(evt);
            }
        });

        alterarColaborador_c.setText("Altera Colaborador");
        alterarColaborador_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarColaborador_cActionPerformed(evt);
            }
        });

        jLabel7.setText("Obs* Não informe Login e senha para usuários");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpf_txt)
                            .addComponent(jLabel3))
                        .addGap(39, 39, 39)
                        .addComponent(nome_c, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(endereco_txt)
                            .addComponent(email_txt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfCpf_c, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email_c, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(end_c, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(incluirCliente_btn))))))
                .addGap(131, 131, 131)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(telegonetelefone_c, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(login_c, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(senhasenha_c))))
                        .addGap(151, 151, 151)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefone_c, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alterarColaborador_c)
                            .addComponent(castrarClaborador_btn))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(alterarCliente_c)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefone_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(telegonetelefone_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(nome_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cpf_txt))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cpfCpf_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jButton2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(login_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(castrarClaborador_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alterarColaborador_c)
                                .addGap(17, 17, 17))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_txt))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endereco_txt)
                            .addComponent(end_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhasenha_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(59, 59, 59)
                        .addComponent(incluirCliente_btn)
                        .addGap(18, 18, 18)
                        .addComponent(alterarCliente_c)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Cadastrar C/Cl", jPanel4);

        jLabel9.setText("Excluir Clente ou colaborador");

        jLabel10.setText("CPF");

        excluirColaborador_btn.setText("Excluir Colaborador");
        excluirColaborador_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirColaborador_btnActionPerformed(evt);
            }
        });

        excluirCliente_btn.setText("Excluir Cliente");
        excluirCliente_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCliente_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(29, 29, 29)
                                .addComponent(excluirColaboradorCliente_c, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(excluirColaborador_btn)
                        .addGap(18, 18, 18)
                        .addComponent(excluirCliente_btn)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(excluirColaboradorCliente_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirColaborador_btn)
                    .addComponent(excluirCliente_btn))
                .addGap(73, 73, 73))
        );

        jLabel20.setText("Nome");

        excluirMaterial_btn.setText("Excluir Material");
        excluirMaterial_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirMaterial_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel20)
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(excluirMaterial_c, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirMaterial_btn))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(excluirMaterial_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(excluirMaterial_btn)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Excluir", jPanel5);

        jLabel11.setText("Insire o CPF do Cliente:");

        jLabel12.setText("Insire o nome do Material");

        jLabel13.setText("Insere a quantidade");

        realizarVendas_btn.setText("Realizar Venda");
        realizarVendas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVendas_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputQuantidadeMaterial_c)
                            .addComponent(inputNomeMaterial_c)
                            .addComponent(inputCpfVenda_c, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(realizarVendas_btn)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(inputCpfVenda_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(inputNomeMaterial_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(inputQuantidadeMaterial_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(realizarVendas_btn)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Realizar Vendas", jPanel7);

        jLabel14.setText("Nome");

        jLabel15.setText("Preco");

        jLabel16.setText("Quantidade");

        jLabel17.setText("Especificação");

        jLabel18.setText("Margem Lucro");

        margemLucro_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                margemLucro_cActionPerformed(evt);
            }
        });

        jLabel19.setText("Fornecedor");

        adicionarMaterial_btn.setText("Adicionar Material");
        adicionarMaterial_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarMaterial_btnActionPerformed(evt);
            }
        });

        alterarMaterial_btn.setText("Aterar Materia");
        alterarMaterial_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarMaterial_btnActionPerformed(evt);
            }
        });

        jLabel21.setText("Data de Fabricão");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantidade_c, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(nomeMaterial_c)
                            .addComponent(preco_c)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especificacao_c)
                            .addComponent(margemLucro_c, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adicionarMaterial_btn)
                            .addComponent(alterarMaterial_btn))
                        .addGap(120, 120, 120))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(32, 32, 32)
                                .addComponent(fornecedor_c, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(13, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(dataFabricacao_c)
                                .addGap(28, 28, 28))))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(nomeMaterial_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(fornecedor_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(dataFabricacao_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(preco_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(quantidade_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adicionarMaterial_btn)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(especificacao_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(margemLucro_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(alterarMaterial_btn)
                        .addGap(47, 47, 47))))
        );

        jTabbedPane1.addTab("Incluir Material", jPanel8);

        jLabel22.setText("Gerar Extrato  de um cliente");

        jLabel23.setText("Informe o CPF:");

        input_cpfExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_cpfExtratoActionPerformed(evt);
            }
        });

        campo_extrato.setColumns(20);
        campo_extrato.setRows(5);
        jScrollPane2.setViewportView(campo_extrato);

        gerar_btn.setText("Gerar");
        gerar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(input_cpfExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22)
                    .addComponent(gerar_btn))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(input_cpfExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(gerar_btn))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gerar Extrato", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirCliente_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCliente_btnActionPerformed
        if(rotas.ExcluirCliente(excluirColaboradorCliente_c.getText())){
            JOptionPane.showMessageDialog(rootPane, "Excluido com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_excluirCliente_btnActionPerformed

    private void excluirColaborador_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirColaborador_btnActionPerformed
        if(rotas.ExcluirColaborador(excluirColaboradorCliente_c.getText())){
            JOptionPane.showMessageDialog(rootPane, "Excluido com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_excluirColaborador_btnActionPerformed

    private void alterarColaborador_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarColaborador_cActionPerformed
        if(rotas.AlterarColaborador(
            login_c.getText(),
            senhasenha_c.getText(),
            nome_c.getText(),
            end_c.getText(),
            email_c.getText(),
            cpfCpf_c.getText(),
            telegonetelefone_c.getText()))
    {
        JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_alterarColaborador_cActionPerformed

    private void alterarCliente_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarCliente_cActionPerformed
        if(rotas.AlterarCliente(
            nome_c.getText(),
            end_c.getText(),
            email_c.getText(),
            cpfCpf_c.getText(),
            telegonetelefone_c.getText()))
    {
        JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_alterarCliente_cActionPerformed

    private void castrarClaborador_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castrarClaborador_btnActionPerformed
        if(rotas.IncluirColaborador(login_c.getText(), senhasenha_c.getText(), nome_c.getText(),
            end_c.getText(),
            email_c.getText(),
            cpfCpf_c.getText(),
            telegonetelefone_c.getText())){
        JOptionPane.showMessageDialog(rootPane, "Cadatrado Com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_castrarClaborador_btnActionPerformed

    private void end_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_end_cActionPerformed

    private void incluirCliente_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirCliente_btnActionPerformed
        if(rotas.IncluirCliente(nome_c.getText(),
            end_c.getText(),
            email_c.getText(),
            cpfCpf_c.getText(),
            telegonetelefone_c.getText())){
        JOptionPane.showMessageDialog(rootPane, "Cadatrado Com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_incluirCliente_btnActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sair_btnActionPerformed

    private void listarColaboradores_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarColaboradores_btnActionPerformed
         jTextPane1.setText(rotas.ImprimirListaColaboradores());
        //JOptionPane.showMessageDialog(rootPane, rotas.ImprimirListaColaboradores());
    }//GEN-LAST:event_listarColaboradores_btnActionPerformed

    private void ListarEstoque_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarEstoque_btnActionPerformed
       // JOptionPane.showMessageDialog(rootPane, rotas.ImprimirEstoque());
        jTextPane1.setText(rotas.ImprimirEstoque());
    }//GEN-LAST:event_ListarEstoque_btnActionPerformed

    private void listarClientes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarClientes_btnActionPerformed

        //JOptionPane.showMessageDialog(rootPane, rotas.ImprimirListaClientes());
        jTextPane1.setText(rotas.ImprimirListaClientes());
    }//GEN-LAST:event_listarClientes_btnActionPerformed

    private void lstarVendas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstarVendas_btnActionPerformed

        jTextPane1.setText(rotas.ConsultarVendas());
    }//GEN-LAST:event_lstarVendas_btnActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        String login=login_input.getText(), senha=senha_input.getText();

        boolean validar;

        if(rotas.login(login, senha)){
            JOptionPane.showMessageDialog(rootPane, "Login efetuado com sucesso!");
            jTabbedPane1.enable(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Login ou senha errado. Tente novamente");
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void senha_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha_inputActionPerformed

    private void margemLucro_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_margemLucro_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_margemLucro_cActionPerformed

    private void adicionarMaterial_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarMaterial_btnActionPerformed
        if(rotas.IncluirMaetrial(
                nomeMaterial_c.getText(),
                Integer.parseInt(quantidade_c.getText()),
                Float.parseFloat(preco_c.getText()),
                especificacao_c.getText(),
                Float.parseFloat(margemLucro_c.getText()),
                fornecedor_c.getText(),
                dataFabricacao_c.getText())){
        JOptionPane.showMessageDialog(rootPane, "Cadatrado Com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_adicionarMaterial_btnActionPerformed

    private void alterarMaterial_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarMaterial_btnActionPerformed
                if(rotas.AlterarMaterial(
                nomeMaterial_c.getText(),
                Integer.parseInt(quantidade_c.getText()),
                Float.parseFloat(preco_c.getText()),
                especificacao_c.getText(),
                Float.parseFloat(margemLucro_c.getText()),
                fornecedor_c.getText(),
                dataFabricacao_c.getText())){
        JOptionPane.showMessageDialog(rootPane, "Alterado Com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_alterarMaterial_btnActionPerformed

    private void excluirMaterial_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirMaterial_btnActionPerformed
                if(rotas.ExcluirMaterial(excluirMaterial_c.getText())){
        JOptionPane.showMessageDialog(rootPane, "Excluido Com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_excluirMaterial_btnActionPerformed

    private void realizarVendas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVendas_btnActionPerformed
        if(rotas.RealizarVenda(
                Integer.parseInt(inputQuantidadeMaterial_c.getText()),
                inputCpfVenda_c.getText(),
                inputNomeMaterial_c.getText()))
        {
            JOptionPane.showMessageDialog(rootPane, "Venda Realizada!");
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro!");
        }
    }//GEN-LAST:event_realizarVendas_btnActionPerformed

    private void numeroClientesColaboradores_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroClientesColaboradores_btnActionPerformed
        jTextPane1.setText(rotas.MostrarColaboradoresClientes());
    }//GEN-LAST:event_numeroClientesColaboradores_btnActionPerformed

    private void input_cpfExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_cpfExtratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_cpfExtratoActionPerformed

    private void gerar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerar_btnActionPerformed
       
        campo_extrato.setText(rotas.GerarExtratoCliente());
    }//GEN-LAST:event_gerar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfeca().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListarEstoque_btn;
    private javax.swing.JButton adicionarMaterial_btn;
    private javax.swing.JButton alterarCliente_c;
    private javax.swing.JButton alterarColaborador_c;
    private javax.swing.JButton alterarMaterial_btn;
    private javax.swing.JTextArea campo_extrato;
    private javax.swing.JButton castrarClaborador_btn;
    private java.awt.Choice choice1;
    private javax.swing.JTextField cpfCpf_c;
    private javax.swing.JLabel cpf_txt;
    private javax.swing.JTextField dataFabricacao_c;
    private javax.swing.JTextField email_c;
    private javax.swing.JLabel email_txt;
    private javax.swing.JTextField end_c;
    private javax.swing.JLabel endereco_txt;
    private javax.swing.JTextField especificacao_c;
    private javax.swing.JButton excluirCliente_btn;
    private javax.swing.JTextField excluirColaboradorCliente_c;
    private javax.swing.JButton excluirColaborador_btn;
    private javax.swing.JButton excluirMaterial_btn;
    private javax.swing.JTextField excluirMaterial_c;
    private javax.swing.JTextField fornecedor_c;
    private javax.swing.JButton gerar_btn;
    private javax.swing.JButton incluirCliente_btn;
    private javax.swing.JTextField inputCpfVenda_c;
    private javax.swing.JTextField inputNomeMaterial_c;
    private javax.swing.JTextField inputQuantidadeMaterial_c;
    private javax.swing.JTextField input_cpfExtrato;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton listarClientes_btn;
    private javax.swing.JButton listarColaboradores_btn;
    private javax.swing.JButton login_btn;
    private javax.swing.JTextField login_c;
    private javax.swing.JTextField login_input;
    private javax.swing.JButton lstarVendas_btn;
    private javax.swing.JTextField margemLucro_c;
    private javax.swing.JTextField nomeMaterial_c;
    private javax.swing.JTextField nome_c;
    private javax.swing.JButton numeroClientesColaboradores_btn;
    private javax.swing.JTextField preco_c;
    private javax.swing.JTextField quantidade_c;
    private javax.swing.JButton realizarVendas_btn;
    private javax.swing.JButton sair_btn;
    private javax.swing.JTextField senha_input;
    private javax.swing.JTextField senhasenha_c;
    private javax.swing.JTextField telefone_c;
    private javax.swing.JTextField telegonetelefone_c;
    // End of variables declaration//GEN-END:variables
}
